### ISSUE TITLE
OpenTherm?

### ISSUE THREAD

**Issue by ringods** [openmotics/3rd-party#1]
Hello,

Thinking of using OpenMotics in a renovation project. Today, I bumped into this announcement (Dutch):

http://www.onemorething.nl/2015/11/nieuwe-nest-thermostaat-voor-europa-beschikbaar/

It seems to support the OpenTherm "standard":

https://en.wikipedia.org/wiki/OpenTherm

How do these compare regarding heating: is a Nest thermostat competing with OpenMotics functionality or can these augment each other?

**Comment by khenderick** [comment]
Hi,

OpenMotics does not support OpenTherm at this moment. It cannot work together with Nest controlling the heating (only one of both should control heating). But there's nothing wrong with OpenMotics being used for lights, inputs, outputs, ... and the Nest for controlling the heating.

For what I know from Nest, it talks to the boiler just like a regular room thermostat would do. However, it's smart in a sense that it learns when it should heat to which temperature. The downside is that e.g. if your living room is on the desired temperature, but you want to heat up the bathroom, you have to do some manual tweaking; temporarily increase the set room temperature and close all [thermostatic radiator valves](http://www.myson.co.uk/static_files/my/images/content/2TRV15DEC_-_cut_out.jpg) in the living room to prevent that one from heating up.

OpenMotics is a bit different there. It is not (yet) smart (enough) that it can learn when it should heat to which temperature, so you have to program it when to heat up to which temperatures (you can off course, just like any other thermostat, temporarily increase the temperature). However, when using OpenMotics, the thermostatic radiator valves that are usually located at the radiator are removed and electric valves are placed onto the [heating distributors](http://i00.i.aliimg.com/img/pb/884/711/409/409711884_949.jpg). This, together with a temperature sensor in every room enables OpenMotics to control the temperature for each individual room, each room with its own temperatures and timings. So you can just turn on the heating for the bathroom alone, or for a bedroom when one of the kids is sick.

I hope this more or less answers all your questions. There's a lot of information [in our wiki](http://wiki.openmotics.com/index.php/Heating_Compatibility). In any case, do not hesitate to let us know if more things would be unclear.
